# Base build on latest Alpine Linux image
FROM alpine:latest AS build

# Install NodeJS and NPM
# The --no-cache option prevents the package index from being cached locally,
# which reduces the size of the image even further.
RUN apk add --no-cache nodejs npm

# Install yarn and Angular CLI
RUN npm install --global yarn @angular/cli

# Copy project files to the docker image
COPY . /app

# Set /app as working directory
WORKDIR /app

# By default, if no other command is provided,
# install packages with yarn and run Angular in dev mode
RUN yarn install && ng build

FROM nginx:alpine AS prod
COPY --from=build /app/dist/frontend /usr/share/nginx/html