name: Test, build and deploy

on:
  push:
    branches: ["main"]

jobs:
  test:
    name: Test frontend using angular tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./frontend
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run angular tests
        run: ng test --watch=false --browsers=ChromeHeadless
        working-directory: ./frontend

  deploy:
    name: Build docker image and push to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/planty-frontend:latest,${{ secrets.DOCKERHUB_USERNAME }}/planty-frontend:${{ github.sha }}
