name: Test, build and deploy

on:
  push:
    branches: ["main", "feature/test-stage-optional-envs"]

jobs:
  test:
    name: Test Quarkus project using Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Postgres database
        run: sudo systemctl start postgresql.service
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Wait for Postgres database to be ready
        run: pg_isready
      - name: Set up Postgres user
        run: sudo -u postgres psql --command="CREATE USER ${{ secrets.PLANTY_DATABASE_USER_TEST }} PASSWORD '${{ secrets.PLANTY_DATABASE_PASSWORD_TEST }}'"
      - name: Create additional database
        run: sudo -u postgres createdb ${{ secrets.PLANTY_DATABASE_NAME_TEST }} --owner=${{ secrets.PLANTY_DATABASE_USER_TEST }} PGPASSWORD=${{ secrets.PLANTY_DATABASE_PASSWORD_TEST }}
      - name: Run Quarkus tests
        working-directory: ./backend
        run: PLANTY_DATABASE_TYPE_TEST=${{ secrets.PLANTY_DATABASE_TYPE_TEST }} PLANTY_DATABASE_USER_TEST=${{ secrets.PLANTY_DATABASE_USER_TEST }} PLANTY_DATABASE_PASSWORD_TEST=${{ secrets.PLANTY_DATABASE_PASSWORD_TEST }} PLANTY_DATABASE_HOST_TEST=${{ secrets.PLANTY_DATABASE_HOST_TEST }} PLANTY_DATABASE_PORT_TEST=${{ secrets.PLANTY_DATABASE_PORT_TEST }} PLANTY_DATABASE_NAME_TEST=${{ secrets.PLANTY_DATABASE_NAME_TEST }} mvn -B verify -Pnative
  deploy:
    name: Build docker image and push to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/planty-backend:latest,${{ secrets.DOCKERHUB_USERNAME }}/planty-backend:${{ github.sha }}
